# ProductOptionGroup:
content:
  '*/*':
    schema:
      type: object
      properties:
        name:
          type: string
          example: "Color"
        options:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: "Red"
              price_offset:
                type: number
                format: double
              asset_ids:
                type: array
                items:
                  $ref: '../schemas/RecordId.yaml'