# Product:
content:
  application/json:
    schema:
      type: object
      properties: 
        name:
          type: string
          example: Sterling Silver Bracelet
        slug:
          type: string
          example: sterling-silver-bracelet-1234
        description:
          type: string
        basePrice:
          $ref: '../schemas/Price.yaml'
        quantity:
          type: integer
          format: uint32
        isActive:
          type: boolean
        categoryId:
          $ref: '../schemas/IdUnion.yaml'
        properties:
          type: object
          properties:
            product: 
              type: object
              properties:
                productType:
                  type: string
                  example: "FineEarring"
                claspType:
                  type: string
                  example: "other-clasp-type"
                chainType:
                  type: string
                  example: "other-chain-type"
                backFinding:
                  type: string
                  example: "clip-on"
                ringSize:
                  type: string
                  example: "3"
            material: 
              type: object
              properties:
                materialType:
                  type: array
                  items:
                    type: string
                    enum: 
                    - "metal"
                    - "gemstone"
                    - "pearl"
                  example: ['metal']
                material:
                  type: array
                  items:
                    type: string
                  example: ['titanium', 'black-diamond']
                gemType:
                  type: string
                stoneCut:
                  type: string
                stoneClarity:
                  type: string
                stoneShape:
                  type: string
                pearlType:
                  type: string
                pearlLuster:
                  type: string
                pearlShape:
                  type: string
                pearlUniformity:
                  type: string
                surfaceMarking:
                  type: string
                stringingMethod:
                  type: string
                sizePerPearl:
                  type: string
                settingType:
                  type: string
                metalType: 
                  type: string
                metalStamp:
                  type: string
                inscription:
                  type: string
        assets:
          type: array
          items:
            $ref: '../schemas/RecordId.yaml'
description: Product object that needs to be added to the store
required: true