# Get Product
get:
  tags:
    - product
  summary: Get a specific product
  operationId: getProduct
  parameters:
    - $ref: '../parameters/identifier.yaml'
  responses:
    '200':
      description: successful get operation
      content:
        application/json:
          schema:
            $ref: '../schemas/Product.yaml'
    '404':
      description: product with provided id not found
# Update Product
patch:
  tags:
    - product
  summary: Update a specific product
  operationId: updateProduct
  parameters:
    - $ref: '../parameters/identifier.yaml'
  requestBody:
    $ref: '../requestBodies/Product.yaml'
  responses:
    '200':
      description: successful update operation
      content:
        application/json:
          schema:
            $ref: '../schemas/Product.yaml'
    '404':
      description: product with provided id not found
  security:
    - bearerAuth: []
# Delete Product
delete:
  tags:
    - product
  summary: Delete a specific product record
  operationId: deleteProduct
  parameters:
    - $ref: '../parameters/identifier.yaml'
  responses:
    '200':
      description: successful delete operation
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                $ref: '../schemas/RecordId.yaml'
              deleted:
                type: boolean
                default: true
  security:
    - bearerAuth: []