# Remove asset from product
delete:
  tags:
    - product
    - asset
  summary: Remove asset from product
  description: |
    Removes the association of an asset from a product. This will not delete the asset, only the relationship to the product.

    If you need to delete all assets at once, you can use PUT /v1/products/prod_123/assets ("Set assets for a product") with an empty payload.
  operationId: deleteProductAsset
  parameters:
    - $ref: '../parameters/identifier.yaml'
    - name: asset_id
      in: path
      description: id of the asset
      required: true
      schema:
        $ref: '../schemas/RecordId.yaml'
  responses:
    '200':
      description: successful update operation
      content:
        application/json':
          schema:
            type: object
            properties: 
              deleted:
                type: boolean
                default: true
  security:
    - bearerAuth: []