# Get a specific variant group for product
get:
  tags:
    - product
  summary: Get a specific option group of a product
  operationId: getProductOptionGroup
  parameters:
    - $ref: '../parameters/identifier.yaml'
    - name: group_id
      in: path
      description: id of the option group
      required: true
      schema:
        $ref: '../schemas/RecordId.yaml'
  responses:
    '200':
      description: successful get operation
      content:
        "*/*":
          schema:
            $ref: '../schemas/ProductOptionGroup.yaml'
    '404':
      description: product with provided id not found
# Update a specific option group of a product
put:
  tags:
    - product
  summary: Update a specific option group of a product
  operationId: updateProductOptionGroup
  parameters:
    - $ref: '../parameters/identifier.yaml'
    - name: group_id
      in: path
      description: id of the option group
      required: true
      schema:
        $ref: '../schemas/RecordId.yaml'
  requestBody:
    $ref: '../requestBodies/ProductOptionGroup.yaml'
  responses:
    '200':
      description: successful update operation
      content:
        "*/*":
          schema:
            $ref: '../schemas/ProductOptionGroup.yaml'
    '404':
      description: product with provided id not found
  security:
    - jwt_bearer: []
# Delete a specific option group of a product
delete:
  tags:
    - product
  summary: Delete a specific product option group of a product
  operationId: deleteProductOptionGroup
  parameters:
    - $ref: '../parameters/identifier.yaml'
    - name: group_id
      in: path
      description: id of the option group
      required: true
      schema:
        $ref: '../schemas/RecordId.yaml'
  responses:
    '200':
      description: successful delete operation
      content:
        "*/*":
          schema:
            type: object
            properties:
              id:
                $ref: '../schemas/RecordId.yaml'
              deleted:
                type: boolean
                default: true
  security:
    - jwt_bearer: []