# Get Product Attribute
get:  
  tags:
    - product
    - product_type
  summary: Get a specific product attribute
  operationId: getProductAttribute
  parameters:
    - $ref: '../parameters/identifier.yaml'
  responses:
    '200':
      description: successful get operation
      content:
        "*/*":
          schema:
            $ref: '../schemas/ProductAttribute.yaml'
    '404':
      description: product with provided id not found
# Update Product Attribute
put:
  tags:
    - product
    - product_type
  summary: Update a specific product attribute
  operationId: updateProductAttribute
  parameters:
    - $ref: '../parameters/identifier.yaml'
  requestBody:
    $ref: '../requestBodies/ProductAttribute.yaml'
  responses:
    '200':
      description: successful update operation
      content:
        "*/*":
          schema:
            $ref: '../schemas/ProductAttribute.yaml'
    '404':
      description: product with provided id not found
  security:
    - jwt_bearer: []
# Delete Product Attribute
delete:
  tags:
    - product
    - product_type
  summary: Delete a specific product attribute
  operationId: deleteProductAttribute
  parameters:
    - $ref: '../parameters/identifier.yaml'
  responses:
    '200':
      description: successful delete operation
      content:
        "*/*":
          schema:
            type: object
            properties:
              id:
                $ref: '../schemas/RecordId.yaml'
              deleted:
                type: boolean
                default: true
  security:
    - jwt_bearer: []