# Create Product
post:
  tags:
    - product
  summary: Add a new active product to the store
  operationId: addProduct
  responses:
    '200':
      description: successful add operation
      content:
        application/json:
          schema:
            $ref: '../schemas/Product.yaml'
    '405':
      $ref: '../responses/IllegalInput.yaml'
    '401':
      $ref: '../responses/UnauthorizedError.yaml'
  requestBody:
    $ref: '../requestBodies/Product.yaml'
  security:
    - bearerAuth: []
# Get multiple Products
get:
  tags:
    - product
  summary: Get a list of active products
  operationId: getProducts
  parameters:
    - $ref: '../parameters/limit.yaml'
    - $ref: '../parameters/page.yaml'
    - $ref: '../parameters/sortBy.yaml'
    - name: categoryId
      in: query
      description: filter by array of category ids. all values must apply to the product
      required: false
      schema:
        $ref: '../schemas/RecordId.yaml'
      style: form
      explode: false
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '../schemas/Product.yaml'
              meta:
                type: object
                properties:
                  pagination:
                    $ref: '../schemas/MetaPagination.yaml'
    '405':
      $ref: '../responses/IllegalInput.yaml'