# /src/paths/product__variants.yaml

# /product/{identifier}/variant:
# Create Variant
post:
  tags:
    - product
  summary: Create a new product variant
  description: |
    Create a new variant, along with options and assets, and assign it to the specified product. 

    A variant is a specific variation of your product, which is made up of a number of variant options. For example, if your product was a T-shirt, your variant groups might be "size" and "color", and each of those may have options such as "small", "medium", etc and "red", "blue", etc. You may have a number of variants, for small + red, small + blue, medium + red, medium + blue, etc.

    You may only have one variant for each combination of variant options (e.g. only one small + red variant).
  operationId: addProductVariant
  parameters: 
    - $ref: '../parameters/identifier.yaml'
  responses:
    '200':
      description: successful add operation
      content:
        "*/*":
          schema:
            $ref: '../schemas/ProductVariant.yaml'
    '405':
      $ref: '../responses/IllegalInput.yaml'
    '401':
      $ref: '../responses/UnauthorizedError.yaml'
  requestBody:
    $ref: '../requestBodies/ProductVariant.yaml'
  security:
    - jwt_bearer: []
# List Variants
get:
  tags:
    - product
  summary: List variants of a product
  description: |
    Returns a list of available variants for the specified product. The list is paginated, however it has a higher default page size (100) compared with other paginated API endpoints.
  operationId: getProductVariants
  parameters: 
    - $ref: '../parameters/identifier.yaml'
  responses:
    '200':
      description: successful operation
      content:
        "*/*":
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '../schemas/ProductVariant.yaml'
              meta:
                type: object
                properties:
                  pagination:
                    $ref: '../schemas/MetaPagination.yaml'
    '405':
      $ref: '../responses/IllegalInput.yaml'
# Update multiple variants
put:
  tags:
    - product
  summary: Update multiple variants
  description: |
    Updates multiple variants at once, using the same request structure as "Update variant" 
    nested within a variants array in the request arguments.
  operationId: updateProductVariants
  parameters:
    - $ref: '../parameters/identifier.yaml'
  requestBody:
    $ref: '../requestBodies/ProductVariants.yaml'
  responses:
    '200':
      description: successful operation
      content:
        "*/*":
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '../schemas/ProductVariant.yaml'
    '405':
      $ref: '../responses/IllegalInput.yaml'
    '401':
      $ref: '../responses/UnauthorizedError.yaml'
  security:
    - jwt_bearer: []
# Delete multiple variants
# delete:
#   tags:
#     - product
#   summary: Delete multiple variants
#   description: |
#     Deletes multiple variants at once from the specified product, by providing an array of variant IDs in the variants request parameter.
#   operationId: deleteProductVariants
#   parameters:
#     - $ref: '../parameters/identifier.yaml'
#   requestBody:
#     content:
#       '*/*':
#         schema:
#           type: object
#           properties:
#             variants:
#               type: array
#               items:
#                 $ref: '../schemas/RecordId.yaml'
#     required: true
#   responses:
#     '200':
#       description: successful delete operation
#       content:
#         "*/*":
#           schema:
#             type: object
#             properties:
#               deleted:
#                 type: integer
#     '405':
#       $ref: '../responses/IllegalInput.yaml'
#     '401':
#       $ref: '../responses/UnauthorizedError.yaml'
#   security:
#     - jwt_bearer: []