# Create option group for product
post:
  tags:
    - product
  summary: Create option group for product
  operationId: addProductOptionGroup
  parameters:
    - $ref: '../parameters/identifier.yaml'
  responses:
    '200':
      description: successful add operation
      content:
        "*/*":
          schema:
            $ref: '../schemas/ProductOptionGroup.yaml'
    '405':
      $ref: '../responses/IllegalInput.yaml'
    '401':
      $ref: '../responses/UnauthorizedError.yaml'
  requestBody:
    $ref: '../requestBodies/ProductOptionGroup.yaml'
  security:
    - jwt_bearer: []
# List multiple option groups for product
get:
  tags:
    - product
  summary: Get a list of option groups for a specific product
  operationId: getProductOptionGroups
  parameters:
    - $ref: '../parameters/identifier.yaml'
  responses:
    '200':
      description: successful operation
      content:
        "*/*":
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '../schemas/ProductOptionGroup.yaml'
              meta:
                type: object
                properties:
                  pagination:
                    $ref: '../schemas/MetaPagination.yaml'
    '405':
      $ref: '../responses/IllegalInput.yaml'