# ProductVariant:
type: object
required:
- options
properties:
  id:
    $ref: './RecordId.yaml'
  sku:
    type: string
  inventory:
    type: integer
    format: uint32
  price:
    $ref: './Price.yaml'
  description:
    type: string
  created:
    $ref: './UnixTimestamp.yaml'
  updated:
    $ref: './UnixTimestamp.yaml'
  options:
    $ref: './ProductOptionsDictionary.yaml'
    # type: array
    # items:
    #   $ref: './ProductOptionKeyValue.yaml'
    # type: array
    # items:
    #   type: object
    #   properties:
    #     variant_group:
    #       $ref: './RecordId.yaml'
    #     variant_option:
    #       $ref: './RecordId.yaml'
  assets:
    type: array
    items:
      $ref: './Asset.yaml'