# ProductOptionGroup:
type: object
required:
  - name
properties:
  id:
    $ref: './RecordId.yaml'
  name:
    type: string
    example: "Color"
  created:
    $ref: './UnixTimestamp.yaml'
  updated:
    $ref: './UnixTimestamp.yaml'
  options:
    type: array
    items:
      $ref: './ProductOption.yaml'