openapi: 3.0.0

###################################
# MCJE API
# 2021-10-15
# Phan Cong Minh (@pcminh)
###################################

info:
  description: |
    This is the OAS document for MCJE Common API
  version: "1.0.0"
  title: Common API for Mimililu & Co. Jewelry E-commerce
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Phan Công Minh
    email: pcminh01@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  # Added by API Auto Mocking Plugin
  # - description: SwaggerHub API Auto Mocking
  #   url: https://virtserver.swaggerhub.com/thefourstooges/mcje-api/1.0.0
  - url: http://localhost:3000/v1
tags:
  - name: product
    description: Products for sale on MCJE
  # - name: product_type
  #   description: Product Type/Class
  - name: category
    description: Groups of products
  - name: asset
    description: Audio/Video/Image asset of a product
  - name: cart
    description: User's cart
  - name: store
    description: Access to store's orders
  - name: Users
    description: User management and retrieval
  - name: Auth
    description: Authentication
  - name: Checkout
    description: Checkout and Order Conversion
paths:
  ## USER.ROUTE.JS
  /users:
    $ref: './paths/users.yaml'
  /users/{id}: 
    $ref: './paths/user.yaml'
  ## AUTH.ROUTE.JS
  /auth/register:
    $ref: './paths/auth__register.yaml'
  /auth/login:
    $ref: './paths/auth__login.yaml'
  /auth/logout:
    $ref: './paths/auth__logout.yaml'
  /auth/refresh-tokens:
    $ref: './paths/auth__refresh-tokens.yaml'
  /auth/forgot-password:
    $ref: './paths/auth__forgot-password.yaml'
  /auth/reset-password:
    $ref: './paths/auth__reset-password.yaml'
  /auth/send-verification-email:
    $ref: './paths/auth__send-verification-email.yaml'
  /auth/verify-email:
    $ref: './paths/auth__verify-email.yaml'
  ## PRODUCTS & PRODUCT OPTION GROUPS
  /product:
    $ref: './paths/products.yaml'
  /product/{identifier}:
    $ref: './paths/product.yaml'
  # /product/{identifier}/option_group:
  #   $ref: './paths/product__option_groups.yaml'
  # /product/{identifier}/option_group/{group_id}:
  #   $ref: './paths/product__option_group.yaml'
  # /product/{identifier}/variant:
  #   $ref: './paths/product__variants.yaml'
  # /product/{identifier}/variant/{variant_id}:
  #   $ref: './paths/product__variant.yaml'
  # /product/{identifier}/asset:
  #   $ref: './paths/product__assets.yaml'
  # /product/{identifier}/asset/{asset_id}:
  #   $ref: './paths/product__asset.yaml'
  # ### PRODUCT TYPES & PRODUCT ATTRIBUTES (i.e. non user choosable)
  # /product/type:
  #   $ref: './paths/product_types.yaml'
  # /product/type/{identifier}:
  #   $ref: './paths/product_type.yaml'
  # /product/attribute:
  #   $ref: './paths/product_attributes.yaml'
  # /product/attribute/{identifier}:
  #   $ref: './paths/product_attribute.yaml'
  ## CATEGORIES
  /category:
    $ref: './paths/categories.yaml'
  /category/{identifier}:
    $ref: './paths/category.yaml'
  ## ASSETS
  /asset:
    $ref: './paths/assets.yaml'
  /asset/{identifier}:
    $ref: './paths/asset.yaml'
  ## CART
  /cart:
    $ref: './paths/carts.yaml'
  /cart/{identifier}:
    $ref: './paths/cart.yaml'
  /cart/{identifier}/items:
    $ref: './paths/cart__items.yaml'
  /cart/{identifier}/items/{item_id}:
    $ref: './paths/cart__item.yaml'
  ## CHECKOUT
  /checkout:
    $ref: './paths/checkout.yaml'
  /checkout/{identifier}: 
    $ref: './paths/checkout-token.yaml'
  ## ORDER MANAGEMENT
  /order:
    $ref: './paths/orders.yaml'
  /order/{identifier}: 
    $ref: './paths/order.yaml'
  /order/{identifier}/add-payment:
    $ref: './paths/order__add-payment.yaml'
  /order/{identifier}/add-fulfillment:
    $ref: './paths/order__add-fulfillment.yaml'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  schemas:
    $ref: './schemas/_index.yaml'
  requestBodies:
    $ref: './requestBodies/_index.yaml'
  securitySchemes:
    $ref: './securitySchemes/_index.yaml'
  parameters:
    $ref: './parameters/_index.yaml'
  responses:
    $ref: './responses/_index.yaml'